---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cert-manager-secrets-generator
  namespace: networking
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./cert-manager-cloudflare-tokens.enc.yaml
