---
securityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 1000
  runAsUser: 1000
  supplementalGroups:
    - 26
    - 303

podAnnotations:
  reloader.stakater.com/auto: "true"

podSecurityContext:
  fsGroup: 1000
  privileged: true # Necessary for hw acceleration.
  supplementalGroups:
    - 26
    - 303

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                # FIXME(ar3s3ru): is there a better way? Ideally it should follow the node where
                # the media-data-v2 PVC is hosted.
                - gladius

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: acme
  hosts:
    - host: jellyfin.nl.ar3s3ru.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts: [jellyfin.nl.ar3s3ru.dev]
      secretName: jellyfin-tls

resources:
  limits:
    gpu.intel.com/i915: "1"
  requests:
    gpu.intel.com/i915: "1"

volumes:
  - name: media-data
    persistentVolumeClaim:
      claimName: media-data-v2

volumeMounts:
  - name: media-data
    mountPath: /data

persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-v2
  media:
    enabled: false # Managed separately and manually.
