# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.1/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  hostNetwork: true # Required for IPv6 detection.
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate

    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        image:
          repository: docker.io/favonia/cloudflare-ddns
          tag: edge-alpine
        probes:
          # FIXME(ar3s3ru): find a way to enable these?
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }
        env:
          PROXIED: false
        envFrom:
          - configMapRef: { name: cloudflare-ddns-env }
          - secretRef: { name: cloudflare-ddns-secrets }
