# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.1/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsUser: 1000

service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8989

ingress:
  tailscale:
    className: tailscale
    enabled: true
    hosts:
      - host: nl-sonarr
        paths:
          - path: "/"
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: [nl-sonarr]

controllers:
  main:
    type: deployment
    replicas: 1
    annotations:
      "reloader.stakater.com/auto": "true"
    containers:
      main:
        env:
          PGID: 1000
          PGUID: 1000
          TZ: Europe/Amsterdam
        image:
          repository: ghcr.io/linuxserver/sonarr
          tag: 4.0.15
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

persistence:
  config:
    enabled: true
    existingClaim: sonarr-config-v2
    globalMounts: [{ path: /config }]
    type: persistentVolumeClaim
  media:
    enabled: true
    existingClaim: media-data-v2
    globalMounts: [{ path: /data }]
    type: persistentVolumeClaim
