# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "kubernetes" {
    secret_suffix  = "nvidia-device-plugin"
    config_path    = "../../../kubeconfig.yaml"
    config_context = "it"
  }
}
