---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflare-ddns-secrets-generator
  namespace: networking
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./cloudflare-ddns-secrets.enc.yaml
