---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nvme-3-replicas
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  fromBackup: ""
  diskSelector: "nvme"
  dataEngine: "v2"
  fsType: "ext4"
  dataLocality: "best-effort"
