---
ingress:
  console:
    enabled: true
    ingressClassName: tailscale
    host: nl-minio
    tls: [{ hosts: [nl-minio] }]

tenant:
  name: minio-tenant
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 2
      size: 6Gi
      storageClassName: longhorn-nvme-replicated
  certificate:
    requestAutoCert: false
  metrics:
    enabled: true
  prometheusOperator: true
  users:
    - name: minio-user-loki
  buckets:
    - name: loki-chunks
      objectLock: true
      region: eu-west-1
    - name: loki-ruler
      objectLock: true
      region: eu-west-1
    - name: loki-admin
      objectLock: true
      region: eu-west-1
