---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: sonoff-zigbee-antenna
  namespace: home-automation
spec:
  capacity: 1
  discoveryHandler:
    name: udev
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60"
