---
apiVersion: v1
clusters:
  - name: nl-private-init
    cluster:
      # certificate-authority-data: <add-here>
      server: https://server-ip:6443
  - name: it
    cluster:
      server: https://tailscale-operator.tail2ff90.ts.net
  - name: nl
    cluster:
      server: https://tailscale-operator-1.tail2ff90.ts.net
contexts:
  # NOTE: this context should only be used during bootstrap!
  #
  # To create a cluster-admin during bootstrap, use the following commands in the machine:
  #
  # $ kubectl create serviceaccount cluster-admin --namespace kube-system
  # $ kubectl create clusterrolebinding cluster-admin --serviceaccount=kube-system:cluster-admin --clusterrole=cluster-admin
  # $ kubectl apply -f - <<EOF
  #   ---
  #   apiVersion: v1
  #   kind: Secret
  #   type: kubernetes.io/service-account-token
  #   metadata:
  #     name: cluster-admin-token
  #     namespace: kube-system
  #     annotations:
  #       kubernetes.io/service-account.name: cluster-admin
  #   EOF
  # $ kubectl get secret cluster-admin-token -n kube-system -o jsonpath='{.data.token}' | base64 -d
  - name: nl-private-admin-init
    context:
      cluster: nl-private-init
      user: nl-cluster-admin
  - name: nl
    context:
      cluster: nl
      user: tailscale-auth
  - name: it
    context:
      cluster: it
      user: tailscale-auth
kind: Config
preferences: {}
users:
  - name: tailscale-auth
    user:
      token: unused
  - name: nl-cluster-admin
    user:
      token: add-here
