---
apiVersion: v1
clusters:
  - name: private
    cluster:
      # certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRjNU1EYzNOamN3SGhjTk1qVXdOVEl5TURrMU5qQTNXaGNOTXpVd05USXdNRGsxTmpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRjNU1EYzNOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUMGpnd3Z5ZTVVcFZWWDZkN01vS0VVUWpjSEhHaGhNK2VUZ3d1Z3lqK3QKYnQwdU10ek91b0xZaFpKS0tOZDUzZ3duV0ozZks0LzFlT1VSZ21idHNsZUlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXpYT2NldjFJclZHa3RNaTdYdGRGCmx6WDByNm93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQk44Ry9iUlZYTEhIV3A3a2dyUEhrazdiRXllKzJGSlYKanV4a0RIOWg1andDSVFDb3RwMjAxcHc0L2J6MWdMeUV2TnYvaVd5OGN1L081ekJzZXpiNlMrWFgrZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://server:6443
  - name: it
    cluster:
      server: https://it-tailscale-operator.tail2ff90.ts.net
  - name: nl
    cluster:
      server: https://tailscale-operator-1.tail2ff90.ts.net
contexts:
  # NOTE: this context should only be used during bootstrap!
  #
  # To create a cluster-admin during bootstrap, use the following commands in the machine:
  #
  # $ kubectl create serviceaccount cluster-admin --namespace kube-system
  # $ kubectl create clusterrolebinding cluster-admin --serviceaccount=kube-system:cluster-admin --clusterrole=cluster-admin
  # $ kubectl apply -f - <<EOF
  #   ---
  #   apiVersion: v1
  #   kind: Secret
  #   type: kubernetes.io/service-account-token
  #   metadata:
  #     name: cluster-admin-token
  #     namespace: kube-system
  #     annotations:
  #       kubernetes.io/service-account.name: cluster-admin
  #   EOF
  # $ kubectl get secret cluster-admin-token -n kube-system -o jsonpath='{.data.token}' | base64 -d
  - name: private-admin
    context:
      cluster: private
      user: cluster-admin
  - name: nl
    context:
      cluster: nl
      user: tailscale-auth
  - name: it
    context:
      cluster: it
      user: tailscale-auth
kind: Config
preferences: {}
users:
  - name: tailscale-auth
    user:
      token: unused
  - name: cluster-admin
    user:
      token: private
