---
logging:
  enabled: true
  level: debug
ffmpeg:
  accel: qsv
  accelDecode: true
  preset: slow
  targetResolution: original
  transcode: required
oauth:
  enabled: true
  autoLaunch: true
  autoRegister: true
  buttonText: "Login with Authelia"
  clientId: immich
  issuerUrl: "https://auth.ar3s3ru.dev/.well-known/openid-configuration"
  mobileOverrideEnabled: false
  scope: "openid email profile"
  signingAlgorithm: "RS256"
  profileSigningAlgorithm: "none"
  storageLabelClaim: "preferred_username"
  storageQuotaClaim: "immich_quota"
