---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cnpg-cluster
  namespace: media
spec:
  # A bug was reported in v0.3.0, which does not allow a replicated setup:
  # https://github.com/immich-app/immich-charts/issues/149#issuecomment-2559012759
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 5Gi
    storageClass: longhorn-nvme-3-replicas

  # Enable superuser access with the secret you created
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: immich-postgresql-postgres

  bootstrap:
    initdb:
      database: immich
      owner: immich
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: immich-cnpg
            spec:
              type: LoadBalancer
              loadBalancerClass: tailscale

  monitoring:
    enablePodMonitor: true
