---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-v3
  namespace: media
spec:
  storageClassName: ""
  volumeName: immich-library-v3-pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
