---
image:
  tag: v1.134.0

# TODO: move postgres out of this.
useDeprecatedPostgresChart: true

server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "acme"
      hosts:
        - host: photos2.ar3s3ru.dev
          paths:
            - path: "/"
      tls:
        - hosts: [photos2.ar3s3ru.dev]
          secretName: immich-tls
  # Needed for hardware acceleration.
  resources:
    requests:
      "gpu.intel.com/i915": "1"
    limits:
      "gpu.intel.com/i915": "1"

postgresql:
  enabled: true
  primary:
    # NOTE: after updating to v1.122.2 the pg node keeps crashing with OOMKilled.
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1024Mi
    service:
      annotations:
        tailscale.com/expose: "true"
    persistence:
      enabled: true
      existingClaim: immich-postgres

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      existingClaim: immich-redis

immich:
  persistence:
    library:
      existingClaim: immich-library
  metrics:
    enabled: true
  configuration:
    logging:
      enabled: true
      level: debug
    ffmpeg:
      accel: qsv
      accelDecode: true
      preset: slow
      targetResolution: original
      transcode: required
    oauth:
      enabled: true
      autoLaunch: true
      autoRegister: true
      buttonText: "Login with Authelia"
      clientId: immich
      issuerUrl: "https://auth.ar3s3ru.dev/.well-known/openid-configuration"
      mobileOverrideEnabled: false
      scope: "openid email profile"
      signingAlgorithm: "RS256"
      profileSigningAlgorithm: "none"
      storageLabelClaim: "preferred_username"
      storageQuotaClaim: "immich_quota"
