---
- id: play_music_in_the_toilet
  alias: Play music in the Toilet
  triggers:
    - alias: Someone entered the Toilet
      trigger: state
      entity_id: binary_sensor.toilet_occupancy
      from: "off"
      to: "on"
  conditions:
    - alias: Check if Home Mode is set to 'Home'
      condition: state
      entity_id: input_select.home_mode
      state: Home
  actions:
    - alias: Start streaming music on the Toilet Speaker
      action: music_assistant.play_media
      target:
        entity_id: media_player.toilet_speaker_2
      data:
        media_type: playlist
        media_id: "soundcloud://playlist/517996875"
    - alias: Turn on shuffling on Toilet Speaker
      action: media_player.shuffle_set
      target:
        entity_id: media_player.toilet_speaker_2
      data:
        shuffle: true

- id: stop_music_in_the_toilet
  alias: Stop music in the Toilet
  triggers:
    - alias: Someone exited the Toilet
      trigger: state
      entity_id: binary_sensor.toilet_occupancy
      from: "on"
      to: "off"
    - alias: "'Sleeping' mode activated"
      trigger: state
      entity_id: input_select.home_mode
      from: Home
      to: Sleeping
  actions:
    - alias: Stop streaming music on the Toilet Speaker
      action: media_player.media_stop
      metadata: {}
      data: {}
      target:
        entity_id: media_player.toilet_speaker_2

- id: enter_sleeping_mode
  alias: Enter 'Sleeping' mode
  triggers:
    - alias: Reached 'Sleeping' time
      trigger: time
      at: input_datetime.sleeping_time
  conditions:
    - alias: Check if Home Mode is set to 'Home'
      condition: state
      entity_id: input_select.home_mode
      state: Home
  actions:
    - alias: Switch to 'Sleeping' mode
      action: input_select.select_option
      target:
        entity_id: input_select.home_mode
      data:
        option: Sleeping

- id: exit_sleeping_mode
  alias: Exit 'Sleeping' mode
  triggers:
    - alias: Reached 'Wake up' time
      trigger: time
      at: input_datetime.wakeup_time
  conditions:
    - alias: Check if Home Mode is set to 'Sleeping'
      condition: state
      entity_id: input_select.home_mode
      state: Sleeping
  actions:
    - alias: Switch to 'Home' mode
      action: input_select.select_option
      target:
        entity_id: input_select.home_mode
      data:
        option: Home
