# yaml-language-server: $schema=https://git.sr.ht/~johnhamelink/hass-json-schema/blob/main/json-schemas/configuration.json
---
default_config:

logger:
  default: info
  logs:
    custom_components.auth_oidc: debug

http:
  cors_allowed_origins:
    - https://nl-hass.tail2ff90.ts.net
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "192.168.2.0/24" # LAN subnet
    - "10.42.0.0/24" # ClusterIP subnet
    - "100.0.0.0/8" # Tailnet

auth_oidc:
  discovery_url: "https://auth.nl.ar3s3ru.dev/application/o/home-assistant/.well-known/openid-configuration"
  display_name: "Log in with Authentik"
  id_token_signing_alg: "RS256"
  client_id: !env_var HASS_OAUTH_CLIENT_ID
  client_secret: !env_var HASS_OAUTH_CLIENT_SECRET
  features:
    automatic_user_linking: true
    automatic_person_creation: true
  claims:
    display_name: name
    username: email
    groups: groups
  roles:
    admin: home-admin
    user: home-member

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_datetime:
  sleeping_time:
    name: Sleeping time
    has_date: false
    has_time: true
    icon: mdi:bed-clock
    initial: "23:00"
  wakeup_time:
    name: Wake up time
    has_date: false
    has_time: true
    icon: mdi:sun-clock
    initial: "07:00"

input_select:
  home_mode:
    name: Home Mode
    options:
      - Home # Someone is at home, normal working conditions
      - Away # Nobody is at home (other than Luna perhaps)
      - Sleeping # Time to sleep and be quiet, no disturbances
      - Vacation # We are away from home for an extended period of time
    initial: Home
    icon: mdi:home-analytics
