telegram_bot_token: ENC[AES256_GCM,data:5+bS4GKI1EXggKP8hY9hOsjarYai49+DgAhJB9PnIfwwO+hgZudqjrGt8UCpgA==,iv:7cbAWSQ54fCDbugKsZ1TYBEKrG1rz1DK5sFPsqa5u+w=,tag:EDu/5clgd/3qoycc+4vvNQ==,type:str]
telegram_chat_id: ENC[AES256_GCM,data:cRCuF14TBEjVVPcatXI=,iv:xkNZvbXvVfJyzURa9zSkCeN6YR9R1hMCYkRD0OhMp4g=,tag:m59eGCNMj9hhSeOi0+pxcw==,type:int]
sops:
    age:
        - recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYWIzMnBDWlJuRWZFc29M
            czIzNWVzVHFIRkpwTlhNT1BEbXpzTVl2N1JBCklSUFBKUjhkNkFjYlZadXFYd0Vt
            VDdIWjZ2S0FNSnFkUVJqbmdNYTQvUFUKLS0tIHZlSUkrREE2RU55ZTczbnViTHhp
            bHg0TXFhSXVaUXRZbDlqYUVBS1pUOHcKDvwBMhb0GG+24BaSUQgkZOuC6AD4+c0w
            gLyv/xUpdd6TeR49JQKNWSV5m6kxaE+CnY7WQAQR791Rk0DotA5HQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T13:03:57Z"
    mac: ENC[AES256_GCM,data:vPY8nG8f60KUSn/ENi+N9BDWEG65DP+WV1TGGLSYGEDhDin9DnQoS1BAXM9cyBobLyGPQPNe8/VAQB+Anu/qzwXb4ks6mexUxMV8oR8pjb0Q4OnnhrgeBssDa+xdj+XwRfxprFyis4h2SKbuf/erIU7mQ48C8LUGNXq/j720Dac=,iv:i0yxPu4lCQKAIbiaV2GGgyKgE+yhwmEB1LsYOpkk/kw=,tag:5fT4Ejsl84rbj5X6FkG8YQ==,type:str]
    pgp:
        - created_at: "2025-08-16T18:58:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAgAgWabB6cX77XTURsqtP7ybxpFLAnCPyzwtw20tgyR3/bM
            VeNKvrzthogy1yCPanu0oWFIg3BolXxzNmds3dp6AiDPvk61ax4kBYlhH9Y8MK2g
            GgfYsYZfxP9kFdviYl0v8AXYr3SjkzYWlRkm10X/vXcJE5l6QzSnns4mWpK1Riry
            bOY4cfAiEQD8/dJvPjznowDTF59VWk00sMGAhnBizH4QZZpe17+jvV0FJ+ewckun
            bIOumWYh8KgXASP9YDpcrBV6vdjxdMUagEAEUtw3Zi9PWRezoOowbDu+iLrTZpY9
            PO24Uit3YuAgT1BqZ7qcI+MxmQWyUnt6rMctYdu9FAf+MzMvjAtFJeXbeUsfJIA2
            L+nehUj29zektgnaY7HQMFiMaCxcVKNqDscbWv/zBBZxFTVA50JvJeNXYoXkcttR
            C9WlUF7brSILoM+XwqSX/x+9lvxCzhO4/XvJAszPNUV17TLqmH9VaxiNgji8bzV7
            Jbtr1lTbupL2+Cicfw2OZSfjm5BNtUOgS3lbDt3K8/hn41ptWWrFVmJbLgdE8xeq
            p9ZXG2u2OTpqTVSCzeWnnSB4ToZLjTJjtqZVMfEFRgwKT+xczGc3I+grbIlOlQyz
            G/CYelrPHxmuI7F44GogdI35mckAKUfsWibkxPCQYQrcpad4ZwFFugYRrVpFB6n8
            jtJeAaHBVhPDkXTn4W+Z4fyjSSN/ERAcfEAmThiuWzPhGvQqUUkQO/tuB9WnXS1L
            Cjoxc6pWOUX/caGUGT/NwyKHNXIotgbBmQUBbR49yJlTmVE5DkL4TMja290RWNaK
            4A==
            =Ctm4
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    unencrypted_suffix: _unencrypted
    version: 3.10.2
