xiaomi_vacuum_host: ENC[AES256_GCM,data:N3rbSMjeKaRwFK8=,iv:gQ9mcFi4WjQ5M36+5LzzFUXosh17qrRW0rsVdkcajG8=,tag:PF96zqlbXvJSav6++yPPtw==,type:str]
xiaomi_vacuum_token: ENC[AES256_GCM,data:w70tY/H+A+a3nkABTPd6MlXDz/3wVFMaO6MuNHb8DCw=,iv:BcL6JKIRQ0eLAx9/d1N1kG0aSzcz2bLRPW+ZcRUzNY4=,tag:2Ft1ECGDaykuFXkv+NjNLA==,type:str]
xiaomi_cloud_username: ENC[AES256_GCM,data:1jYOncoHg3V+UP52Hi8UEzB5OmPzUOU=,iv:eAqDTVF37BHvGVF5JsaXn6xfWXURBWT1eaiXoCrnc0c=,tag:vTV41NC8V5dTC8mDL3h7Kg==,type:str]
xiaomi_cloud_password: ENC[AES256_GCM,data:EwzWyM6oL/w25SMU/3Mn,iv:XhnzYLvEjzqgttvDvGkBsk8dv3gLVEbMHT+6cLlm1y0=,tag:KfiqyMLT2C3m2dgctoKmSg==,type:str]
sops:
    age:
        - recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUd1OVU2bktyVFRGc3Ux
            UE9ESisyTjF6cUowNWxieEMyMnhVSUxveWdzCkxiOEI1TlJMd2VBc2NkbmRHNWkx
            aGw1SnNkWTBEa3lwODl1QXE0YXB2dVUKLS0tIFlObG02SnBTWk95M0pIWHVtYmk2
            MmpHMStwVXZsRG5TWittMWFIN00wVjAKzWo1bwJTLcGwAFwaj3PpAodKhCroh4yq
            oMlMtHjflqxUhEVlffWMq2iaBNzebWvypSu0smnr4+9wM4b70RDb0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T15:37:50Z"
    mac: ENC[AES256_GCM,data:7PzYNSRzc0qH82BJrcPoqRUvP9f+anEHDlovD7hUlvv+hwNPgURbPXumEBlJIhAtq7VQnis5fV/TezmDYchYs4vN0jYGhje88iN++1bwEIQS/59pvwxffFhhyNUiFU9EQR/46w5cTqfjWYPlKD9aUTVjj0QsngKfsTZgUMIvOIo=,iv:r4AN8ULd6XrZl++tSjWtK50XQut9AqEG5I4YJxNWmjg=,tag:D53wq1V0EHNPeWd/5AvgWg==,type:str]
    pgp:
        - created_at: "2025-05-18T15:19:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf8DX9anVoNygtgCLTq8nP/8hdvhPR/emOUOOJ3d3ADxpv1
            nga70w/w315KpRfRnMpWwSs+7POzUl2SN39ZBedJqVqKgZUhfGxs36end7IpaQJj
            k4s73rmN74ZF2U8wp+5VZodRnf2TJ6zs/63O4n3NiwYu5eLgBoofpnJilGYpG3U7
            PlZludRIlq6AkvAewZKIeU/suCp2eO6OCIVg50SQ4xGnrPbaPxdcmgrCkN3c9kJe
            laDGjDhwforJoA1UALr+4sAjkxBPf7h9Uy3nZmoQD2TDPGJ9KhRkFMZVVC/pICZA
            gIq3S3IAHlmBs1dunBLrTe3Ob+0I0YuXISJ2+kViFgf/fhrAcO2Iz+GCOmky9YZR
            31IKAVx2rQxsEHFpyDkHoJ/0FKUKjf0Q1AlpcvxaP22MOK+zNk0c7fyZwqzoOt9Q
            cvQMqyRDwPcmtWuqNC4A10d33bgMb/QJeB0WqnLizs2tgd3LR0grgAQ4YgKGWNpX
            sGF6vTAKPPgoDno5s6ywyxtYuLIGqM0qTyau6qScGSImLdpIHTWXRTSE3u5xBsx4
            iYyKdUneaynHpjznw+lOJ4H/bc2xwEizuZZYao81cnPaNAP3tAyRESB4jCoATzHy
            Muo19u3euKWyaRzrmBsio/jKqtM1EoJ75EqCSiVHP/1IofFHNssqPS8eqE+yHNoW
            E9JeAdLPZwBeyduBu1UyV2n/T+v7EjXxElHOpAWYgnwIngaCtwNaFFn4eRds2ekN
            f9zUoxREuJBPb3c8tu3eUvQFvZ8OkeUg+LSgVVyu+2AVRcFmRJT1oVCTflYhHT0p
            IQ==
            =8LHj
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    unencrypted_suffix: _unencrypted
    version: 3.10.2
