---
image:
  tag: v1.133.0

# TODO: move postgres out of this.
useDeprecatedPostgresChart: true

server:
  ingress:
    main:
      enabled: true
      ingressClassName: tailscale
      annotations:
        # Exposes the service to the internet through Tailscale Funnel
        tailscale.com/funnel: "true"
      hosts:
        - host: immich
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich

postgresql:
  enabled: true
  primary:
    # NOTE: after updating to v1.122.2 the pg node keeps crashing with OOMKilled.
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1024Mi
    persistence:
      enabled: true
      existingClaim: immich-postgres

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      existingClaim: immich-redis

immich:
  persistence:
    library:
      existingClaim: immich-library
  metrics:
    enabled: true
  configuration:
    logging:
      enabled: true
      level: log
    oauth:
      enabled: true
      autoLaunch: true
      autoRegister: true
      buttonText: "Login with Authelia"
      clientId: immich
      issuerUrl: "https://auth.ar3s3ru.dev/.well-known/openid-configuration"
      mobileOverrideEnabled: false
      scope: "openid email profile"
      signingAlgorithm: "RS256"
      profileSigningAlgorithm: "none"
      storageLabelClaim: "preferred_username"
      storageQuotaClaim: "immich_quota"
