---
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: flugg-cluster
  namespace: k3k-system
spec:
  mode: shared
  version: v1.32.4-k3s1 # Same as k3s version.
  servers: 3
  tlsSANs:
    - flugg-cluster
  # nodeSelector:
  #   disktype: ssd
  expose:
    ingress:
      ingressClassName: tailscale
  # clusterCIDR: 10.42.0.0/16
  # serviceCIDR: 10.43.0.0/16
  # clusterDNS: 10.43.0.10
  serverArgs:
    - --tls-san=flugg-cluster.tail2ff90.ts.net
  persistence:
    type: dynamic
    storageClassName: longhorn-nvme-3-replicas
