---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  repo: https://kyverno.github.io/kyverno
  chart: kyverno
  version: 3.7.1
  targetNamespace: kyverno-system
