---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: akri
  namespace: kube-system
spec:
  repo: https://project-akri.github.io/akri/
  chart: akri
  version: 0.13.8
  targetNamespace: kube-system
  valuesContent: |-
    prometheus:
      enabled: true

    udev:
      discovery:
        enabled: true
