---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: radarr
  namespace: media
spec:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  version: 4.6.2
  targetNamespace: media
  valuesContent: |-
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000

    service:
      main:
        type: ClusterIP
        controller: main
        ports:
          http:
            port: 7878

    ingress:
      tailscale:
        className: tailscale
        enabled: true
        hosts:
          - host: nl-radarr
            paths:
              - path: "/"
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: [nl-radarr]

    controllers:
      main:
        type: deployment
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            env:
              PGID: 1000
              PGUID: 1000
              TZ: Europe/Amsterdam
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: 6.1.1@sha256:15417a594ebda4c660a9fa9748e7199d33e2d17b31bbc5ad7ba2e86f0b414763
            probes:
              liveness: { enabled: false }
              readiness: { enabled: false }
              startup: { enabled: true }

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v2
        globalMounts: [{ path: /config }]
        type: persistentVolumeClaim
      media:
        enabled: true
        existingClaim: media-data-v4
        globalMounts: [{ path: /data }]
        type: persistentVolumeClaim
