---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-v3-pv-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.lan
    path: /mnt/zpool-nl-01/pvc-fccb9cfc-aef5-4d93-a9db-5a6314e0796a
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=300
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-v3
  namespace: media
spec:
  storageClassName: ""
  volumeName: media-data-v3-pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
