# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: argocd-ksops-age-keys
    namespace: argo-system
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:MqfFYwmck80WPynk/nwatDWub3ChR+7+UjyEKw0Z59Ri/6+yVkf+25KUwz+/PcH+plClo1YVM+lHvkljBFhuFtbLcMi9JaH32c5GEkJOOlr2lwhB1HFBewmDH8qAnjnDzLwOBEQG0hkFM+v7KLEPYSRZYAEWf2sEyEw0tWs8BiNsYthp/dP1Q64McG/datU9aJIPcO+JmJE5SPY6ZmRg+YXKr4abjuOkifmOh/H4TV6QJuywmvmyX5bxkana,iv:5jFLmI7VDJNnWzlvAGR1Dtk/IrPW7J2F/tRi/wUNTKc=,tag:7nLjwDVvAeQKnXP8FRzZcg==,type:str]
sops:
    age:
        - recipient: age18eehnlpn44hpk4d823zfnkq72vqmf6kqhrh009uwdajneeaqzskqscx589
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTlJBSGFVYWFzYUxGc1V2
            WXZWb05OVDBkUmxSOHh5bXN6cDlONDNzL0JRCkljczBMZFQ2TSs1VG03WlJrM2JH
            bzlXUDIyNkdXZWhraVNMRmlsam8weDgKLS0tIHJ2STVDTmQya2poVXFHUkQzRVFD
            Z24xMmhHem1jKzV0ZElNd3N0UGpsdGsKyoKoN9i7JBHAJFOjPic9WCrddTkQeqsH
            e25pt5tqi2JwUwDa49tPKLgE8GPxTnNWyobjhTfjkRFkFS7N1ihUGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1krvwskkgw5f3ufcwgl6l2jz0emxnkn40wpup2aqhqdulqy2x99js4p5fnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z2kra2VGRTQ1eTEwWmZ3
            Yk9kSG1DblVnSHIrWDYralRYdllFOEo5eDBnCmpKalg0d2lYbHhpelVTWHdXazJP
            SzB5QXJYam1xQ2VyQVBUOFJtWllKQ1kKLS0tIHVza3Q1a0krUGlZL0trQ0FtV0R2
            STJZV2p5b2hFQnVRVUtFekZ6U214bk0KGfPiGTgBnN1BGSIB6totZjOIliIjijsQ
            /VT3aOM5WKCxWFVjd5nBpbNG173NMUXWvRNUK7R+B4r0igUi+hWC/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age143yn95y2n546rlqrhgy2nzrz0w87ks7fk9dlwp3ylt0dfflczuhqrv2lmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eGhnVWc2R3BWZWNxRDhk
            eXVMQUVYYnlZV3NGSG5ZdlpLY0lVbHliWEJvCkFDd0FpNzFySmhHNUI0eUcrYVB5
            TWgyNFdPdHovODVnUktFWmtzV0V0Y1UKLS0tIFcyYk1PWG9oU284QmV1d3QvNTFP
            R2dCWjJ3RDU2Y3ZUa0JhMmUrQ0lWNWsK1C6y6bNL1IhknP+3FECBsZCKIE6Scet5
            IdfsmUNsOi7ei6gSYCmD04U92VElcEp/prYADzR2OrTCJ4IwFH1Vrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n6eedefn6afu4e2f492xhfhckrayvp65jp7hla3x4nwj2zwz7sasw6ls6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M0NXVElPWTRmbDNic1pE
            bkxkMkpjOTU0cWhRZHZPaHdlQjNGbkE3WHlJCkk4Qk5JUVVLUU8yTUJ0VE8wVWRE
            WVdVbDh3UFFxMklhTWhvTHc0SkN1b3cKLS0tIGN4YXFtTkZLRzhsdWNlMXp6WWhi
            d0tNT1VMMExMaEx2akh0RERTTXd0cDgKGp+VjqOrIh7VcXU8bGFerRmO6m9oT7bj
            Q/IgS5MAiOMJjtRmDdm6xsK55xISf1bIoAkx6Js11VzA4oPpcJ4pYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g62sqmpz4pztx8zn94n8rxzklj7fj805g78m50kxu44yqy26azs2vph2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWlFlZFhXd2xITG10aDFr
            Sy9LdExTU014MU1lNEVtMmVvSjVRUEl4NmlBCk5BbG1SUmlXaXhZZ1phV2xLNDRl
            SldtY0VNQkJxNmsvZ1lYaGRUZzJsYjAKLS0tIDRCaWFSZjBhamlLSkxOMng0SjNa
            Rk5MTk5oaVFkNGF3NDVnYTRJRUd6KzAKcIvY5C1W75Ec8Uk2d/NV5l7B2VcCInv7
            KD7EeJt1LXijdyOBh0yP2R3Y3C3emEPMfcbqVMXoyk/P4EthDqD2VA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tcaqw9c5sfdys359kzs2t599d2sje7sg7fha8ts42955qk9t3yss075kcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6czFLZ04xR0FRdEJSR2xX
            bmRPV2RJei9VSUJhS1NQNldOWXhDM0ZLbzNvCmhuSDFxQzhHS2JnM3hXbFAyYXYw
            ak1pbkpNK2NCVy9YRVhMSDVrQVQ4dTgKLS0tIFRkbGJkWEhSU0I2WlpXdEtqM0Fp
            M3VXVnZ3eUNhcUpTT2tvdm5ZQk5OKzAKBkphH7Nx39kv6Lb7OrGRSmNhQljPhQcu
            sBEAeyFdjsrvbjeAF30jkdsxGrflt7Qk71H2YkWa6Cqyf+Czb+g0Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T18:44:35Z"
    mac: ENC[AES256_GCM,data:7VHm4vCcuMi/H6AVAEqrsemayMRIJeWiUQGmlQmawOFWJANqO+aoSUlBNJuBYPeFpSDPmdcLcaaEnn0QrmLd3lv6Crkqu/Ycx1uN62+7WhB+5nh8mDH3yOJDXk4b3zPJo6cc1iAHYNYIcxsTturCZOgcutpeYU8ScPft477K1wM=,iv:xni0frRvwz9/nFUPufXgGCqVXtoioc6yPIhpf8bR4Qs=,tag:KcxJz3bNdcB/GwnqjU/Esw==,type:str]
    pgp:
        - created_at: "2026-05-26T16:08:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/Tu6pDptk8mT2coVboDvfubKrCD0KYG//FQzFH7xrM9vY
            wOtiA3XMvPJXtDshIJkLrSHvqCx7h5eHNz8Fif8mqc7+zTI6LsctqJ5A1Xdb5LeE
            nRFbInk3SZPh1gvTkWRI0fsPmC/fdHjzBQvnN3LmZ+CB/cthQi9aW98V6Zjrz8NU
            Q63xwoxFWiCrAX/l8DudZHJipmd+P/U5mdcvB//u7qFD/cn4r5NyUqEwLs3V3lcO
            I++K80XbJPqxdYL/HGRC4vG4X7USBuArJqGt1rU2UjeCpY5ThKeHgKOg9eNMI7E1
            kK8C5LVaQEtXFr/hQHjF6YSEbcwhXGAKArG9dUuDHwf/Qp2aO8P4qRmGFOv2gpwH
            /P6SNen9oBVIXhGg2wjobJ0+VXyOP8jVv8XYFQNE/2mvW+ybibpZt5OEfrHJE2JS
            CXFHttcv347bxEGjIPMDO6tXZwGcNLDb7W9WFrPfx1S8v9L+etCcTo576rIiO4YU
            ZjE0SUk2UCgH6KVOv7OkV6I28tUdoKvWyxYweKc6nqUKuES+XqG0l6ksx4E+iUt7
            VgJDlXRyY4T/YpZP6okkG3jGmjSiYvdOk+QJa4OslCKvu7DjYenn9AQ1Dfz4EMCo
            JXKwoanBAOG/91nPL+GNWfZck+dHVeBwR6EmMcskcNP/UESPkCjRZCEd/D51trWt
            dtJeAXer35LaTn/dpCAET3DPl5pSZQ8Nfm9KHDxHzTtlmrvHWKp4HphoQSm+3dqF
            v56PDKaiap+QotD0RKZmwJ+d2fkhh6o20kNJywKET9157RFzQrwebWlmiSxExasl
            bA==
            =SLKi
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
