---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: in-nl-cianfr-one
  namespace: networking
spec:
  endpoints:
    # FIXME(ar3s3ru): Hardcoded KPN public IPv4. Update after moving to new ISP.
    - dnsName: in.nl.cianfr.one
      recordType: A
      recordTTL: 300
      targets:
        - 86.80.120.59
    # FIXME(ar3s3ru): Hardcoded KPN GUA prefix. Update after moving to new ISP.
    - dnsName: in.nl.cianfr.one
      recordType: AAAA
      recordTTL: 300
      targets:
        - 2a02:a469:9060:3::1
