---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: router-v4
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 10.0.0.1
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: router-v6
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: fd00:cafe::1
