---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
    - metallb-pool
  aggregationLength: 32
  aggregationLengthV6: 128
