---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-pool
  namespace: metallb-system
  annotations:
    # To ensure metallb is installed first.
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 10.10.0.0/16
    - fd00:cafe:10::/48
