---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
  annotations:
    # To ensure metallb is installed first.
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
    - metallb-pool
    - k8s-pool
