---
envFromSecret: grafana-secrets-env

# NOTE: the server root URL is set below in "grafana.ini".
ingress:
  enabled: true
  ingressClassName: tailscale
  hosts: [&host nl-grafana]
  tls:
    - hosts: [*host]

annotations:
  reloader.stakater.com/auto: "true"

sidecar:
  datasources:
    enabled: true
    searchNamespace: ALL
  dashboards:
    enabled: true
    searchNamespace: ALL
  alerts:
    enabled: true
    searchNamespace: ALL
  plugins:
    enabled: true
    searchNamespace: ALL
  notifiers:
    enabled: true
    searchNamespace: ALL

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-operated.telemetry.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: false
        basicAuth: false
      - name: AlertManager
        type: alertmanager
        uid: alertmanager
        url: http://alertmanager-operated.telemetry.svc.cluster.local:9093
        access: proxy
        editable: false
        basicAuth: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default

grafana.ini:
  server:
    root_url: https://nl-grafana.tail2ff90.ts.net
  auth:
    disable_login_form: true
  auth.generic_oauth:
    enabled: true
    auto_login: false
    name: Authelia
    icon: signin
    client_id: grafana
    # client_secret: # NOTE: set as an environment variable.
    scopes: openid profile email groups
    empty_scopes: false
    auth_url: https://auth.ar3s3ru.dev/api/oidc/authorization
    token_url: https://auth.ar3s3ru.dev/api/oidc/token
    api_url: https://auth.ar3s3ru.dev/api/oidc/userinfo
    login_attribute_path: preferred_username
    groups_attribute_path: groups
    name_attribute_path: name
    use_pkce: true
    role_attribute_path: contains(groups[*], 'admin') && 'Admin' || 'Editor'
