# yaml-language-server: $schema=https://nl-frigate.tail2ff90.ts.net/api/config/schema.json
---
mqtt:
  host: "emqx.home-automation.svc.cluster.local"
  port: 1883

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: false

record:
  enabled: true
  retain:
    days: 1
    mode: all

go2rtc:
  streams:
    e1-zoom-01:
      - rtsp://{FRIGATE_E1_ZOOM_01_RTSP_USERNAME}:{FRIGATE_E1_ZOOM_01_RTSP_PASSWORD}@192.168.2.45/h264Preview_01_main
      - "ffmpeg:e1-zoom-01#audio=opus"
    e1-zoom-01-sub:
      - rtsp://{FRIGATE_E1_ZOOM_01_RTSP_USERNAME}:{FRIGATE_E1_ZOOM_01_RTSP_PASSWORD}@192.168.2.45/h264Preview_01_sub
      - "ffmpeg:e1-zoom-01-sub#audio=opus"
    e1-zoom-02:
      - rtsp://{FRIGATE_E1_ZOOM_02_RTSP_USERNAME}:{FRIGATE_E1_ZOOM_02_RTSP_PASSWORD}@192.168.2.34/h264Preview_01_main
      - "ffmpeg:e1-zoom-02#audio=opus"
    e1-zoom-02-sub:
      - rtsp://{FRIGATE_E1_ZOOM_02_RTSP_USERNAME}:{FRIGATE_E1_ZOOM_02_RTSP_PASSWORD}@192.168.2.34/h264Preview_01_sub
      - "ffmpeg:e1-zoom-02-sub#audio=opus"

cameras:
  living-room:
    live:
      stream_name: e1-zoom-01-sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/e1-zoom-01?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/e1-zoom-01-sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
  office:
    live:
      stream_name: e1-zoom-02-sub
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/e1-zoom-02?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/e1-zoom-02-sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
