---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attic-data
  namespace: default
  annotations:
    recurring-job-group.longhorn.io/no-recurring-job: enabled
spec:
  storageClassName: longhorn-nvme-2-replicas
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
