---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: attic-secrets-generator
  namespace: media
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./attic-config.enc.yaml
