# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39.1/json-schema/configuration.json
---
theme: "dark"

log:
  level: info
  format: json

telemetry:
  metrics:
    enabled: true

default_2fa_method: totp

authentication_backend:
  refresh_interval: 1m
  ldap:
    enabled: true
    implementation: custom
    address: ldap://lldap.auth.svc.cluster.local:3890
    start_tls: false
    user: uid=admin,ou=people,dc=ar3s3ru,dc=dev
    password: { secret_name: "authelia-secrets" }
    base_dn: dc=ar3s3ru,dc=dev
    additional_users_dn: ou=people
    additional_groups_dn: ou=groups
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    groups_filter: "(&(member=uid={input},ou=people,dc=ar3s3ru,dc=dev)(objectClass=groupOfNames))"
    attributes:
      distinguished_name: "distinguishedName"
      username: "uid"
      mail: "mail"
      member_of: "memberOf"
      group_name: "cn"

password_policy:
  standard:
    enabled: true
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

session:
  cookies:
    - domain: ar3s3ru.dev
      subdomain: auth

  redis:
    enabled: true
    deploy: true
    host: "authelia-redis-headless.auth.svc.cluster.local"

storage:
  postgres:
    enabled: true
    address: "tcp://aws-0-eu-central-1.pooler.supabase.com:5432"
    database: "postgres"
    username: "postgres.akdwzhfsjzmlsfeenlfe"
    password: { secret_name: "authelia-secrets" }

notifier:
  smtp:
    enabled: true
    enabledSecret: true
    subject: "{title}"
    address: "submission://smtp.gmail.com:587"
    username: "nl.homelab.ar3s3ru@gmail.com"
    password: { secret_name: "authelia-secrets" }

identity_providers:
  oidc:
    enabled: true
    cors:
      allowed_origins_from_client_redirect_uris: true
      endpoints: [userinfo, authorization, token, revocation, introspection]

    claims_policies:
      # https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter
      default:
        id_token: [email, email_verified, alt_emails, name, preferred_username, groups]
      username_email:
        id_token: [email, email_verified, alt_emails, name, preferred_username]

    jwks:
      - algorithm: RS256
        use: sig
        key:
          path: '/secrets/authelia-secrets/oidc.jwk.RS256.pem'

    clients:
      - client_id: 'immich'
        client_name: 'Immich'
        client_secret: { path: "/secrets/authelia-oidc-secrets/immich.client_secret.key" }
        public: false
        consent_mode: implicit
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://immich.tail2ff90.ts.net/auth/login'
          - 'https://immich.tail2ff90.ts.net/user-settings'
          - 'https://photos.ar3s3ru.dev/auth/login'
          - 'https://photos.ar3s3ru.dev/user-settings'
          - 'app.immich:///oauth-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
      - client_id: 'home-assistant'
        client_name: 'Home Assistant'
        client_secret: { path: "/secrets/authelia-oidc-secrets/hass.client_secret.key" }
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        consent_mode: implicit
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://nl-hass.tail2ff90.ts.net/auth/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        id_token_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_post'
