---
default_config: {}
logger:
  default: info
  logs:
    custom_components.auth_oidc: debug
http:
  cors_allowed_origins:
    - https://nl-hass.tail2ff90.ts.net
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "10.42.0.73"
    - "100.0.0.0/8"
auth_oidc:
  discovery_url: "https://nl-auth.tail2ff90.ts.net/application/o/home-assistant/.well-known/openid-configuration"
  display_name: "Log in with Authentik"
  id_token_signing_alg: "RS256"
  features:
    automatic_user_linking: true
    automatic_person_creation: true
  claims:
    display_name: name
    username: email
    groups: groups
  roles:
    admin: home-admin
    user: home-user
