---
default_config: {}
logger:
  default: info
  logs:
    custom_components.auth_oidc: debug
http:
  cors_allowed_origins:
    - https://nl-hass.tail2ff90.ts.net
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "192.168.2.0/24" # LAN subnet
    - "10.42.0.0/24" # ClusterIP subnet
    - "100.0.0.0/8" # Tailnet

auth_oidc:
  discovery_url: "https://auth.nl.ar3s3ru.dev/application/o/home-assistant/.well-known/openid-configuration"
  display_name: "Log in with Authentik"
  id_token_signing_alg: "RS256"
  features:
    automatic_user_linking: true
    automatic_person_creation: true
  claims:
    display_name: name
    username: email
    groups: groups
  roles:
    admin: home-admin
    user: home-member

script:
  play_music_in_the_toilet:
    alias: Play music in the Toilet
    sequence:
      - service: media_player.play_media
        target:
          entity_id: media_player.toilet_speaker
        data:
          media_content_id: '{ "app_name": "youtube", "playlist_id": "PLSlWCUnZ5deDcEWu50m_I-iCgIfm0jqv9", "media_id": "CoHD4weW5NI" }'
          media_content_type: cast
    mode: single
    icon: mdi:youtube
