---
default_config: {}
logger:
  default: info
http:
  cors_allowed_origins:
    - https://nl-hass.tail2ff90.ts.net
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "10.42.0.73"
