# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.7.3/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        # These machines have better performances for transcoding,
        # so Jellyfin will likely be scheduled over one of these nodes.
        #
        # To avoid performance bottlenecks between downloading node and consuming node,
        # better to have them placed on the same node.
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - eq14-001

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: &webui 8080
  torrent:
    controller: main
    type: LoadBalancer
    ports:
      bt-tcp:
        port: &torrent 30963
        nodePort: 30963 # Needed for opening the firewall on the host and on the gateway.
        protocol: TCP

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: nl-torrent
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts: [nl-torrent]

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: qbittorrent-config
    globalMounts: [{ path: "/config" }]
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-data
    globalMounts: [{ path: "/data" }]

controllers:
  main:
    type: deployment
    replicas: 1

    annotations:
      "reloader.stakater.com/auto": "true"

    containers:
      main:
        image:
          repository: "ghcr.io/linuxserver/qbittorrent"
          tag: "5.1.0"
        env:
          TZ: "Europe/Amsterdam"
          PGUID: 1000
          PGID: 1000
          WEBUI_PORT: *webui
          TORRENTING_PORT: *torrent
        probes:
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }
