---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: opencloud-secrets-generator
  namespace: media
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./opencloud-secrets.enc.yaml
