---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: slskd-secrets-generator
  namespace: media
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./slskd-secrets.enc.yaml
