---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-v3
  namespace: media
spec:
  storageClassName: ""
  volumeName: media-data-v3-pv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
