---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-videos-v1
  namespace: media
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
