---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-v3-pv-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.lan
    path: /mnt/zpool-nl-01/pvc-fccb9cfc-aef5-4d93-a9db-5a6314e0796a
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=300
