---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argo-system-secrets-generator
  namespace: argo-system
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./ticket-printer-repository.enc.yaml
