---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation

# TODO(ar3s3ru): re-enable this.

# resources:
#   - n8n-cnpg-cluster.yaml
#   - helmrelease-redis.yaml
#   - helmrelease.yaml

# generators:
#   - ksops.yaml
