---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-cnpg-cluster
  namespace: home-automation
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  enableSuperuserAccess: true

  storage:
    size: 4Gi
    storageClass: longhorn-nvme-3-replicas

  bootstrap:
    initdb:
      database: n8n
      owner: n8n

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: n8n-cnpg
            spec:
              type: LoadBalancer
              loadBalancerClass: tailscale
          updateStrategy: patch

  monitoring:
    enablePodMonitor: true
