apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZCGI65p8259nHDF/wVoSgJ1HxRn4U69CAYl6XM5aFmLEvUUfs4t3j6rLBX2irAygXOgbhpkiAI2xil7xzk73,iv:TSN21HyKttaG3ooDlpBZrRCgPKpv5PI4+CCMuyHSuBY=,tag:11aiNPcO5MyadUWPKkkLnA==,type:comment]
    #ENC[AES256_GCM,data:glINk9MbQa4Zf3ub0i/PW9lr9gVRtJnOe6ZrwYbzJjh5SRcMPibHlaPXNke6BaBC6V97rtrlvANGwuIQWh3VuILZlL9W8oYf,iv:eOFquJewB9NznmVa41tgPn0UTvSsCuPfS0G3MixvW7U=,tag:GoByKkQLTZO6l4lS2U0yIg==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:sI0l+R/jd8Tbi7rbnl/P/ILAKXLwioGg3HjPM0yHlxmFogd6g3m9FeLZxWEyYpE8Xi1zJiPn6vBjNSWID2cfLw==,iv:jB9Mt6ExyD8w9hUPaT2KoJgcAZ9ZvpYU2E9yacM93iE=,tag:Ygh6Eo3iXEI6DCwoaU0AVQ==,type:str]
sops:
    age:
        - recipient: age1m38eu4srfs6puqtrpcazlu5kv24fd57yda4p505k9msqjwzttujs825kzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa1hSOVczbGpGNDdMam9C
            M09QVEpGTFV4NnZJZUdCQjlEVjVPNHMxVFR3CnlSVkt2VEVmbjhxelYzWlVoYjdG
            aFB3c3ROY3FMc2RDTkJUaWVEeHdsNVkKLS0tIHlMWGFlSGlOenpDVUF4a1J1d3RP
            Wll6WlNwRzRkcXhxN3hpd2d3R1lyc1kKLpLl9KoEc0j/tkqR5nameCBOn90sLJk6
            ikScOCpilamOZL/Wnb+4pgTKRkFzsK/Ybku+37/W1kpQLvW4h/qUtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T12:53:03Z"
    mac: ENC[AES256_GCM,data:x5kwerQDZor73fROOJCOnB83sFWWRzdgaeVkyWkZzkZjCsuZkyJcjozE6N5Ph9GdWkOth4NGPs0l3W/wyyk3I0Iirkh+uJHrVe3TYoFXOoLUGzFAVNgoDL24kAHsUpTduuzY9OVHvk9zIqen2w++CCnWg0WsWySN96PbZuXHNQM=,iv:a3KQVUWu9VCMvA8k+3gLNbQfftgSp22LxeDsEEZ1oNo=,tag:AGqFEs1EEuSePGySK6Qt7g==,type:str]
    pgp:
        - created_at: "2026-04-18T12:53:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIOA4TLBMScuBokEAf/QMrX8n1jeRD3eF+PQHLXv57qOhf8Su/hkM4roAv7cxVd
            4zseQ/YTVLFFqwpTnVQRkFqHyOghuon1j+QyKrGZhFJZKyr0Q4yUU4HMsnJADl8W
            ruckNjV+1MohOz2UOhB9iuPIVLlDJtJfLiD22IS87wOypEMrDgmkz2Kzm/cbgRSh
            a8MTkvqSChJGXPL2PYXb0WpzAgMKYUbXQtqgxcpZ8iyu9RbWxUBo9u7co4b62YcD
            UBGpQgZQms2S93M3qhPegjC84CpORbuL0R4UCxy4jESqH3nmIRk/5CSDGOGt8Wxp
            uPxsE+ol5Fl7oCPyFElg206C0szLh4AkSpeQSqGirAf+LLxP4kOevPjZ72JF8DnE
            W29pG93ZEAXKpTurGo4uu4DeFZ31kAYVVFPCFV0rq24paevjH3uCOT2SkuC7L5Zb
            W9h3h4QuysHpkQtYqaWUuu26zUzdoF4q+9a+M4DiivNXiF3/Aq5MELBj+YAgVz2o
            SkF8Spy0bBNBkt80ZcZ6N57+lV9JHFTWT7uqB02CqgFKKiBCS7lI7Bdr62XAqE4V
            TQ1cAloUXjUqYg04xEwZ24OauRB+lpLPHsKuH/fHtXewiDfDR7aaqVcnmbHOwxs5
            stp4IBBrZR7UKznfLXmlABsYzSDvvFOstgDEOsHZ9cTeV9NDc+BjEOYzkqFhtTA8
            09JeASRqEx/s+ir2vlwjmQzr8HUpx2oIfoD4NuSaVcTjx4nbWQkvjevf1bnJJnka
            D7Nz8Z8EPa/PU63vikheI2odho3apdxeFn3lIfJwkRMNdDf0nweKrCuFe08DwJ0V
            hw==
            =zK/A
            -----END PGP MESSAGE-----
          fp: C8DAE39DAA00FF97
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
