---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: truenas-nfs-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./truenas-nfs-driver-config.enc.yaml
