# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1883
    runAsGroup: 1883
    fsGroup: 1883
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault

controllers:
  main:
    type: deployment
    replicas: 1
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: docker.io/library/eclipse-mosquitto
          tag: 2.1.2-alpine
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 1883
              initialDelaySeconds: 5
              periodSeconds: 10
          readiness: *probe
        securityContext:
          runAsNonRoot: true
          runAsUser: 1883
          runAsGroup: 1883
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      mqtt:
        port: 1883
      ws:
        port: 1882

persistence:
  config:
    enabled: true
    type: configMap
    name: mosquitto-config
    globalMounts:
      - path: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        readOnly: true
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: mosquitto-data
    globalMounts:
      - path: /mosquitto/data
  log:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /mosquitto/log
