---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-6h
  namespace: longhorn-system
spec:
  cron: "0 */6 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 4
  concurrency: 2
