---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.2/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-groups
  namespace: auth
data:
  admin.json: '{"name":"admin"}'
  home-admin.json: '{"name":"home-admin"}'
  home-member.json: '{"name":"home-member"}'
  media-admin.json: '{"name":"media-admin"}'
  media-viewer.json: '{"name":"media-viewer"}'
  ocis-admin.json: '{"name":"ocis-admin"}'
  ocis-spaceadmin.json: '{"name":"ocis-spaceadmin"}'
  ocis-member.json: '{"name":"ocis-member"}'
  ocis-guest.json: '{"name":"ocis-guest"}'
