# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.1/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  # DEBT(ar3s3ru): since Home Assistant integration targets the Music Assistant
  # through its IP rather than an hostname, using hostNetwork means that the
  # integration will break if Kubernetes schedules the pod on a different node
  # than previously.
  hostNetwork: true # Required for certain network features.

controllers:
  main:
    type: deployment
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/music-assistant/server
          tag: "2.6"
        env:
          LOG_LEVEL: info
        probes:
          # FIXME(ar3s3ru): find a way to enable these?
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8095 # Source: https://github.com/music-assistant/server/blob/dev/Dockerfile#L71

ingress:
  tailscale:
    enabled: true
    className: tailscale
    hosts:
      - host: &host nl-mass
        paths:
          - path: /
            pathType: Prefix
            service: { identifier: main, port: http }
    tls:
      - hosts:
          - *host

persistence:
  tmp:
    enabled: true
    type: emptyDir
    globalMounts: [{ path: /tmp }]
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: music-assistant-data-v2
    globalMounts: [{ path: /data }]
