# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.1/charts/other/app-template/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  main:
    type: deployment
    strategy: RollingUpdate
    replicas: 0 # FIXME(ar3s3ru): set to 1 again when the third node comes back
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          # FIXME(ar3s3ru): use a stable tag once available.
          # Also note, this version is not available on ghcr.io.
          repository: docker.io/fallenbagel/jellyseerr
          tag: "preview-OIDC"
        env:
          TZ: Europe/Amsterdam
          LOG_LEVEL: info
        probes:
          # FIXME(ar3s3ru): find a way to enable these?
          liveness: { enabled: false }
          readiness: { enabled: false }
          startup: { enabled: true }

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 5055

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: acme
    hosts:
      - host: jellyseerr.ar3s3ru.dev
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - jellyseerr.ar3s3ru.dev
        secretName: jellyseerr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: jellyseerr-config-v2
    globalMounts: [{ path: /app/config }]
